name: Create releases

on:
  push:
    tags:
        - v*


jobs:
    process_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get tag version
              id: tag_name
              run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
            - name: Get repo name
              id: repo_name
              run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | sed -e "s/:refs//")
            - name: Build a release
              run: |
               echo ${{ github.event_name }}
               bash create_release.sh $SOURCE_TAG
              env:
               SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
               SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
               GITHUB_REPO: ${{ steps.repo_name.outputs.REPOSITORY_NAME }}
              
